### ISSUE TITLE
Creación Register

### ISSUE THREAD

**Issue by pabloboo** [DSO-TECHINFO/bancodelapeseta-frontend#3]
# Creación de Register

## Captura del Diseño de la Página
![Diseño de la Página](url_de_la_imagen)

## Referencia de la issue para más información
https://docs.google.com/document/d/1fJmXHWKZ5oBKwuTQxudEloaodLqGxMd7yy2lDo2nafM/edit 

## Descripción en Detalle de la Tarea
En esta pantalla se puede registrar un nuevo usuario. El usuario del sistema introduce la siguiente información del cliente: email, número de teléfono, nombre de usuario, contraseña y rol.

Si la operación se ha realizado correctamente debe aparecer un mensaje de éxito y se procede con la confirmación del correo.
Los posibles errores que hay que mostrar en pantalla son: "La contraseña no cumple con la política" y "El usuario ya existe".

## Detalles de la petición
POST /api/v1/auth/register
{
	"email": "user@user.com",
     "phone_number":"11-2424-2424",
	"username":"alejandro",
	"password": "contrasena123"	
}

**Comment by rafazf** [comment]
![image](https://github.com/DSO-TECHINFO/bancodelapeseta-frontend/assets/65522736/2cf9b3b0-a360-46d1-a4c8-9474dbc750b0)
![image](https://github.com/DSO-TECHINFO/bancodelapeseta-frontend/assets/65522736/0e59f416-8024-42b5-9fe1-1f4f5c71b21a)
![image](https://github.com/DSO-TECHINFO/bancodelapeseta-frontend/assets/65522736/5767956e-1fc2-408b-bef9-3ebc8df7111c)
