### ISSUE TITLE
Creación Login

### ISSUE THREAD

**Issue by pabloboo** [DSO-TECHINFO/bancodelapeseta-frontend#4]
# Creación de Login

## Captura del Diseño de la Página
![Diseño de la Página](url_de_la_imagen)

## Referencia de la issue para más información
https://docs.google.com/document/d/1qhoZBYifzh-7MiGgVIsQFIkU39opzmV7DkGI2P8bfvc/edit 

## Descripción en Detalle de la Tarea
En esta pantalla el usuario puede iniciar sesión en su cuenta. Para realizarlo debe introducir su nombre de usuario y su contraseña. Si el usuario se loguea correctamente se debe redirigir a la pantalla de inicio.

Los posibles errores que hay que mostrar en pantalla son: 
- BadCredentialsException: "Credenciales incorrectas. Por favor, verifica tu nombre de usuario y contraseña."
- LockedException: "Tu cuenta está bloqueada temporalmente. Inténtalo de nuevo más tarde."
- DisabledException: "Cuenta deshabilitada. Por favor, verifica tu correo electrónico."

## Detalles de la petición
POST /api/v1/auth/login
{
	"username": "national_id",
	"password": "contrasena123"
}

**Comment by rafazf** [comment]
![image](https://github.com/DSO-TECHINFO/bancodelapeseta-frontend/assets/65522736/e786403e-8d73-4adb-807c-053b60b6a41f)
